language: cpp
compiler:
  - gcc

before_install:
  # g++ 4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  # boost
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  # update repo
  - sudo apt-get update -qq

install:
  # g++ 4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq gcc-4.8 g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  # cmake
  - sudo apt-get install cmake
  # hd5
  - sudo apt-get install libhdf5-serial-dev
  # boost
  - sudo apt-get install libboost1.55-all-dev

script: 
  - "cmake ."
  - $CXX --version
  - "make"
