language: cpp
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install cmake
  - sudo apt-get install libboost-program-options-dev
  - sudo apt-get install libhdf5-serial-dev

script: 
  - "cmake ."
  - "make"
